DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS MusicAlbum;

CREATE TABLE Item (
  id INT GENERATED ALWAYS AS IDENTITY,
  archived BOOLEAN NOT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE Genre (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE Author (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL
  last_name VARCHAR(50) NOT NULL
);

CREATE TABLE MusicAlbum (
  id INT PRIMARY KEY,
  genre_id INT NOT NULL,
  publish_date DATE NOT NULL,
  on_spotify BOOLEAN NOT NULL,
  FOREIGN KEY (id) REFERENCES Item(id),
  FOREIGN KEY (genre_id) REFERENCES Genre(id)
);